---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-hub-ui
data:
  API_URL: 'https://api.hub.tekton.dev'
  API_VERSION: ''
  AUTH_BASE_URL: ''
  REDIRECT_URI: ''
  CUSTOM_LOGO_MEDIA_TYPE: 'image/png'
  CUSTOM_LOGO_BASE64_DATA: ''
